name: Lint
on:
  push:
    branches: [main] # デフォルトブランチだけ実行
  pull_request:
    branches: [main] # main への PR だけ検証
    types: [opened, synchronize, reopened] # PR の更新時に実行
  workflow_dispatch:
jobs:
  ruff:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
    steps:
      - uses: actions/checkout@v6
      - name: Install Python
        uses: astral-sh/setup-uv@v7
      - name: Run Ruff
        run: uv run ruff check --output-format=github
      - name: Generate SARIF file
        if: ${{ !cancelled() }}
        run: uv run ruff check --output-format=sarif --output-file=ruff.sarif
      - name: Upload SARIF file
        if: ${{ !cancelled() }}
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ruff.sarif
  pylint:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
    steps:
      - uses: actions/checkout@v6
      - name: Install Python
        uses: astral-sh/setup-uv@v7
      - name: Run Pylint
        run: uv run pylint main.py --output-format=github
  ty:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
    steps:
      - uses: actions/checkout@v6
      - name: Install Python
        uses: astral-sh/setup-uv@v7
      - name: Run ty
        run: uv run ty check --output-format=github
